#!/usr/bin/env python3
"""
PR Analyzer — N09 Change Viewpoint
Analyzes git diff output for security and reliability regressions.
Skip if no git diff available.
"""

import re
import sys
import json
import argparse
import subprocess
from pathlib import Path
from typing import Dict, List, Optional


# ──────────────────────────────────────────────
# Security / Reliability patterns to flag in diffs
# ──────────────────────────────────────────────

ADDED_LINE_CHECKS = [
    ("SEC-01", "HIGH", "Hardcoded API key added",
     r"\+.*AIzaSy[A-Za-z0-9_-]{30,}"),
    ("SEC-02", "HIGH", "API key logged to console",
     r"\+.*console\.(log|warn|error).*VITE_GEMINI_API_KEY"),
    ("SEC-03", "HIGH", "Hardcoded model name instead of constant",
     r"\+.*['\"]gemini-\d+\.\d+-(pro|flash)-(preview|image)['\"]"),
    ("REL-01", "HIGH", "try/catch removed (reliability regression)",
     r"\-\s*try\s*\{"),
    ("REL-02", "MID", "finally block removed",
     r"\-\s*finally\s*\{"),
    ("REL-03", "MID", "Fallback model reference removed",
     r"\-.*ANALYSIS_FALLBACK|IMAGE_GEN_FALLBACK"),
    ("PRO-01", "HIGH", "TRANSFORMATION DIRECTIVE removed from rightSide",
     r"\-.*TRANSFORMATION DIRECTIVE"),
    ("PRO-02", "MID", "GENERATE IMAGE NOW trigger removed",
     r"\-.*\[GENERATE IMAGE NOW\]"),
]

REMOVED_LINE_CHECKS = [
    ("REL-04", "HIGH", "isGenerating guard removed",
     r"\-.*isGenerating"),
    ("SEC-04", "HIGH", "Image type validation removed",
     r"\-.*image/(jpeg|png|webp)"),
]


def get_git_diff(target: Path) -> Optional[str]:
    """Get git diff for the target directory."""
    try:
        result = subprocess.run(
            ["git", "diff", "HEAD", "--", str(target)],
            capture_output=True, text=True, cwd=target if target.is_dir() else target.parent
        )
        if result.returncode != 0 or not result.stdout.strip():
            # Try staged diff
            result = subprocess.run(
                ["git", "diff", "--cached", "--", str(target)],
                capture_output=True, text=True, cwd=target if target.is_dir() else target.parent
            )
        return result.stdout if result.stdout.strip() else None
    except FileNotFoundError:
        return None


def analyze_diff(diff: str, verbose: bool) -> List[Dict]:
    """Check git diff lines for security/reliability regressions."""
    findings = []

    for check_id, priority, desc, pattern in ADDED_LINE_CHECKS:
        matches = re.findall(pattern, diff, re.MULTILINE)
        if matches:
            findings.append({
                "id": check_id,
                "priority": priority,
                "description": desc,
                "result": "FAIL",
                "detail": f"Found {len(matches)} occurrence(s) in diff",
            })
            if verbose:
                print(f"  ❌ [{priority}] {check_id}: {desc}")
        else:
            if verbose:
                print(f"  ✅ {check_id}: {desc}")

    return findings


def generate_report(findings: List[Dict], diff_available: bool) -> str:
    """Format PR analysis as markdown."""
    if not diff_available:
        return "# PR Analyzer Report — N09\n\n> No git diff available. Skipped.\n"

    high_count = sum(1 for f in findings if f["priority"] == "HIGH" and f["result"] == "FAIL")
    verdict = "✅ PASS" if high_count == 0 else "❌ FAIL"

    lines = [
        "# PR Analyzer Report — N09",
        f"**Verdict:** {verdict}",
        f"**Blocking issues:** {high_count}",
        "",
        "## Diff Analysis",
        "",
        "| ID | Priority | Result | Description |",
        "|----|----------|--------|-------------|",
    ]
    for f in findings:
        emoji = "✅" if f["result"] == "PASS" else "❌"
        lines.append(
            f"| {f['id']} | {f['priority']} | {emoji} {f['result']} | "
            f"{f['description']} — {f.get('detail', '')} |"
        )

    lines += ["", "---", "*Generated by pr_analyzer.py — N09 Code Reviewer*"]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="N09 PR Analyzer")
    parser.add_argument("target", help="Path to node app directory")
    parser.add_argument("--verbose", "-v", action="store_true")
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--output", "-o", help="Write report to file")
    args = parser.parse_args()

    target = Path(args.target)
    print(f"🚀 Running PR Analyzer...")
    print(f"📁 Target: {target}")

    diff = get_git_diff(target)
    if not diff:
        print("ℹ️  No git diff found — skipping PR analysis.")
        report = generate_report([], diff_available=False)
        if args.output:
            Path(args.output).write_text(report, encoding="utf-8")
        sys.exit(0)

    print(f"📋 Diff size: {len(diff)} chars")
    if args.verbose:
        print("\n── Diff Checks ──")

    findings = analyze_diff(diff, args.verbose)
    high_count = sum(1 for f in findings if f["priority"] == "HIGH" and f["result"] == "FAIL")
    verdict = "PASS" if high_count == 0 else "FAIL"

    print(f"\n{'✅' if verdict == 'PASS' else '❌'} Overall: {verdict} ({high_count} blocking issues)")

    report = generate_report(findings, diff_available=True)
    if args.output:
        out_path = Path(args.output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(report, encoding="utf-8")
        print(f"📝 Report written to {out_path}")
    elif not args.json:
        print("\n" + report)

    if args.json:
        output = json.dumps({"verdict": verdict, "high_count": high_count, "findings": findings},
                            indent=2, ensure_ascii=False)
        if args.output:
            Path(args.output).write_text(output, encoding="utf-8")
        else:
            print(output)

    sys.exit(0 if verdict == "PASS" else 1)


if __name__ == "__main__":
    main()
